use_small_heuristics = "Max"
combine_control_expr = false
condense_wildcard_suffixes = true
fn_single_line = true
merge_imports=true
use_field_init_shorthand=true
use_try_shorthand=true
wrap_comments=true
blank_lines_upper_bound=2
unstable_features=true
edition="Edition2018"
imports_layout="HorizontalVertical"